### ISSUE TITLE
add short validation

### ISSUE THREAD

**Issue by WeiliangChenOIST** [CNS-OIST/STEPS_Validation#1]
Hi, @FrancescoCasalegno , could you also add the short validations to here as well please? For users it is easier to just clone this repository and run all validations (short and long) in 1~2 commands.

Also, do we have parallel efield validation (parallel rallpack)?

**Comment by FrancescoCasalegno** [comment]
Hi @WeiliangChenOIST,

1. Putting short validation tests here as well (how? (a) two directories `validation-short` and `validation-long` or (b) all tests in the `validation` dir?) would introduce file duplicates from the other repo. Wouldn't this create some issues in terms of maintainability?

2. Validation for parallel efield is still work in progress but certainly necessary to add. I will take care of that asap.

**Comment by WeiliangChenOIST** [comment]
@FrancescoCasalegno  For validations we don't expect significant changes once the scripts are settled, so it shouldn't be a big problem. But is it possible to let HBP_STEPS and STEPS pull the validations from here instead of keep their local copies?

**Comment by FrancescoCasalegno** [comment]
I discussed you proposal with Adrien. It seems that keeping things as they are now would be better for the sake of continuous integration, also to avoid to download at every time from different repo etc. 
@adevress for more details.

**Comment by WeiliangChenOIST** [comment]
Keeping multiple copies are fine, we don't expect great changes from established validations anyway, but since normal users do not have continuous integration support, it is important to provide an easy access to the complete validation set for them.

**Comment by FrancescoCasalegno** [comment]
Added validation test `validation/validation_efield_mpi/test_rallpack1_dist.py` for rallpack1 distributed using tetopsplit + petsc efield solver.

The test is run by `run_validation_mpi_test.py`, which is replacing `run_validation_rd_mpi_tests.py`.
