### ISSUE TITLE
cp folder under validation_cp

### ISSUE THREAD

**Issue by WeiliangChenOIST** [CNS-OIST/STEPS_Validation#2]
@FrancescoCasalegno I remember you have a problem running validation_cp without the cp folder under it. Is the problem fixed, or we need to add the folder here?

**Comment by FrancescoCasalegno** [comment]
I already fixed that issue by adding the lines
`dir_checkpoint = "validation_cp/cp"`
`if not os.path.exists(dir_checkpoint):`
`    os.makedirs(dir_checkpoint)`
to the file `csd_clamp.py`

**Comment by WeiliangChenOIST** [comment]
@FrancescoCasalegno Is it guaranteed that csd_clamp is the first script to be executed in thecp validation? if not you may need to add the same thing in masteq_diff_cp.py and unbdiff_cp.py
